# Generated by Django 5.2.5 on 2025-09-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Unique room number (e.g., 101).', max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per night in USD.', max_digits=10)),
                ('is_available', models.BooleanField(default=True, help_text='Is the room available for booking?')),
            ],
        ),
    ]
