# Generated by Django 5.2.5 on 2025-09-02 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Room availability status.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(help_text='Room number.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per night.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
