version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=prod
    env_file:
      - ./.env.prod
    depends_on:
      - db
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:8000 pmsapi.wsgi:application

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=pms_user
      - POSTGRES_PASSWORD=pms_password
      - POSTGRES_DB=pms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
