# Generated by Django 5.2.5 on 2025-09-03 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
        ('rooms', '0002_alter_room_is_available_alter_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price for the booking.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(help_text='Booked room.', on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
    ]
